services:
  api:
    build:
      context: .
      dockerfile: api.c0r.ai/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - ml
      - pay
  ml:
    build:
      context: .
      dockerfile: ml.c0r.ai/Dockerfile
    env_file: .env
    ports:
      - "8001:8001"
  pay:
    build:
      context: .
      dockerfile: pay.c0r.ai/Dockerfile
    env_file: .env
    ports:
      - "8002:8002" 