version: '3.8'
services:
  api:
    build: ./api.c0r.ai
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - ml
      - pay
  ml:
    build: ./ml.c0r.ai
    env_file: .env
    ports:
      - "8001:8001"
  pay:
    build: ./pay.c0r.ai
    env_file: .env
    ports:
      - "8002:8002" 