name: c0r_app
description: c0r.ai consumer app (Phase 1 tracker MVP)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  fl_chart: ^0.66.2
  image_picker: ^1.1.2
  mobile_scanner: ^4.0.1
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  supabase_flutter: ^2.5.6
  sentry_flutter: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/env/
